data <- read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";", na.string = "?")
test <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
newDateTime <- strptime(paste(test$Date, test$Time), format = "%d/%m/%Y %H:%M:%S")
newtest <- data.frame(test, DateTime = newDateTime)
with(newtest, plot(DateTime, Global_active_power, type="l", xlab = "", ylab = "Global Active Power(kilowatts)"))
dev.copy(png, filename="Plot2.png", width = 480, height= 480, units ="px")
dev.off()