data <- read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";", na.string = "?")
test <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
hist(test$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power(kilowatts)")
dev.copy(png, filename="Plot1.png",width = 480, height= 480, units ="px")
dev.off()