data <- read.table(file = "household_power_consumption.txt", header = TRUE, sep = ";", na.string = "?")
test <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
newDatetime <- strptime(paste(test$Date, test$Time), format = "%d/%m/%Y %H:%M:%S")
newtest <- data.frame(test, DateTime = newDateTime)
with(newtest, plot(DateTime, Sub_metering_1, type="l", col = "black", xlab = "", ylab = "Energy sub metering"))
lines(newtest$DateTime, newtest$Sub_metering_2, type="l", col = "red")
lines(newtest$DateTime, newtest$Sub_metering_3, type="l", col = "blue")
legend("topright",c("Sub_Metering_1", "Sub_Metering_2", "Sub_Metering_3"), lty=c(1,1), lwd=c(1,1), col = c("black","red", "blue"), cex = 0.75)
dev.copy(png, filename="Plot3.png", width = 480, height= 480, units ="px")
dev.off()